services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incuca-backend
    restart: unless-stopped
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:Hg+D2qwOYM5y1Jw30o0mVBdYufM4lzhWFoCJoWio0vA=
      APP_DEBUG: true
      JWT_SECRET: TqxEnikvQA83MSR7z2krtWqOpeQm2oXiXu9ztH4JmuE7yGrh5qcTdKT2wHW27fS2
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: incuca
      DB_USERNAME: incuca
      DB_PASSWORD: secret
      GEEK_JOKES_API_URL: https://geek-jokes.sameerkumar.website/api
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/var/www
    networks:
      - incuca-network

  frontend:
    build:
      context: ./MoodStateApp
      dockerfile: Dockerfile
      args:
        VITE_API_URL: /api
    container_name: incuca-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - incuca-network

  db:
    image: mysql:8.0
    container_name: incuca-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: incuca
      MYSQL_USER: incuca
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - incuca-network
    command: --default-authentication-plugin=mysql_native_password

networks:
  incuca-network:
    driver: bridge

volumes:
  db_data:
