services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: incuca-backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      APP_NAME: Laravel
      APP_ENV: ${APP_ENV}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      GEEK_JOKES_API_URL: https://geek-jokes.sameerkumar.website/api
    depends_on:
      - db
    networks:
      - incuca-network

  frontend:
    build:
      context: ./MoodStateApp
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: incuca-frontend
    restart: unless-stopped
    ports:
      - "${FRONTEND_PORT}:80"
    depends_on:
      - backend
    networks:
      - incuca-network

  db:
    image: mysql:8.0
    container_name: incuca-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    networks:
      - incuca-network
    command: --default-authentication-plugin=mysql_native_password
  tunnel:
    image: cloudflare/cloudflared:latest
    container_name: incuca-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${TUNNEL_TOKEN}
    networks:
      - incuca-network
networks:
  incuca-network:
    driver: bridge

volumes:
  db_data:
